### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by wouam31200** [djangopbx/djangopbx-install.sh#2]
Hi,

I'm trying to install debian 12 for testing.
Everything seems to be going well except at the end:

```
You are about to create a superuser to manage DjangoPBX, please use a strong, secure password.
Hint: Use the email format for the username e.g. <user@liello.test.liello.cloud>.
Press any key to continue  
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default Access controls? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default Email Templates? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default Modules data? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default SIP profiles? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default Switch Variables? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default Music on Hold data? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Number Translation data? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Conference Settings? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default Settings? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Default Provision Settings? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Yealink Provision Settings? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Yealink vendor provision data? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Load Menu Defaults? y
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

Set up crontab? y

Show database password? y
5a6470b0391b036258e5

Show system password? y
ffb6b7cf-68c7-4952-9705-2b9a5e97f73d
Created symlink /etc/systemd/system/multi-user.target.wants/freeswitch.service → /lib/systemd/system/freeswitch.service.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.

Installation Complete.
```

During the installation I am root.
Thank you so much.

**Comment by AdrianFretwell** [comment]
It looks like the python virtual environment has not been set up properly or for some reason it is not getting activated.
The mandatory use of a venv is new in Debian12 so the install script has not had very much testing.

Having said that, if you got as far as create superuser then the database migrate and the data load of the user groups must have worked OK, which would suggest the venv is fine.

I will run a few more Debian12 installs and report back.

In the meantime would you try an su - django-pbx
You should then get a prompt that looks like: (envdpbx) django-pbx@xxxx:~$
If you see the (envdpbx) then chances are the virtual environment is OK, you can then try the create superuser

cd pbx
python3 manage.py createsuperuser

Thankyou for helping to test the install!
Adrian.

**Comment by wouam31200** [comment]
Hi Adrian,

```
root@djangopbx:~# su - django-pbx
(envdpbx) django-pbx@djangopbx:~$ cd pbx
(envdpbx) django-pbx@djangopbx:~/pbx$ python3 manage.py createsuperuser
Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django-pbx/pbx/manage.py", line 22, in <module>
    main()
  File "/home/django-pbx/pbx/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
(envdpbx) django-pbx@djangopbx:~/pbx$ 
```

With pleasure for the test!

**Comment by AdrianFretwell** [comment]
Replacing the requirements.txt file solves the issue.
There were some incorrect version numbers reported by the pip freeze output owing to the inclusion of --system-site-packages
I have also updated the nginx config.

Please download the latest installer and requirements file and run from a clean build of Debian12.

I will mark this as closed and thank you again for your help.
Adrian.
